[workspace]
resolver = "2"

members = [
    "shame_derive",
    "shame",
    "examples/*",
]

exclude = [ "examples/hot_reload" ]

[profile.dev]
split-debuginfo = "unpacked"

# [profile.dev.package.shame]
# opt-level = 3
